spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: amine
    password: amine3349E
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    profiles:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: localhost
    port: 1025
    username: amine
    password: amine3349E
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret: A93AB956874882B7F5119683F119D
      expiration: 1200000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account